### ISSUE TITLE
Version 10 Breaking Changes 

### ISSUE THREAD

**Issue by yyyc514** [highlightjs/highlight.js#2273]
Creating an issue to keep track of all the "breaking changes" I'd like to do when we get around to major release time.

- [x] Expose parse tree, renderer, and new emitter API. #2404 
- [x]  Rename `cs.js` to `csharp.js`
- [x]  Rename `tex.js` to `latex.js`
- [x] No prohibition against using ES2015 features in the codebase (will cut out a few older browsers we currently technically might support)
- [x] Review ":common" group for potential removals
- [x] remove older onload hook, keeping newer DOMContentLoaded. 
- [x] remove `darkula.css` (mispelling)
- [x] remove `restoreLanguageAPI` (version 9 compressed languages are not compatible with version 10)
- [x] <del>Good time to split C/C++ with a common foundation if we have anyone to work on that</del> Create C/C++ dependency on 'c-like' to prevent future breaking changes https://github.com/highlightjs/highlight.js/issues/2146
- [x] consider XML/PHP entanglement and how to resolve https://github.com/highlightjs/highlight.js/issues/2330
- [ ] **[in progress]** Fix-up `htmlbars` and `handlebars` dependencies https://github.com/highlightjs/highlight.js/issues/2181
- [x] 3rd party language grammar official packaging format https://github.com/highlightjs/highlight.js/issues/2328
- [x] New build system https://github.com/highlightjs/highlight.js/issues/1759
- [ ] Resolve build inconsistency issues: https://github.com/highlightjs/highlight.js/issues/2291
- [x] Switch to createElement vs NS

Thing that probably aren't making it into 10.0

-  Consider deprecating `endSameAsBegin` and encourage callback use instead https://github.com/highlightjs/highlight.js/pull/2261
-  auto highlighting should return a list of possible matches, not just top two
-  Change `highlight(name, x, x, x)` API to `highlight(code, options={})`, we'd still support the legacy API until 11.0 I'd imagine. https://github.com/highlightjs/highlight.js/issues/2277
-  add `baseLanguage` to some language grammars and  https://github.com/highlightjs/highlight.js/issues/2275

**Comment by yyyc514** [comment]
Closing out, so close.  Remaining issues will stand on their own (and may not make it into v10).
