### ISSUE TITLE
Version 11.0 checklist

### ISSUE THREAD

**Issue by joshgoebel** [highlightjs/highlight.js#2558]
This is still a ways away but I wanted to start a list of the breaking changes we intend to introduce so we don't forget anything later.

- [x] rip out beforeMatch in lue of multi-match?
- [x] `.title--class` or `.title__class` #3081
- [x] Throttle deprecation logging #3069
- [x] Remove `lexemes`

---

- [x] Pull Vue plugin out of main build
- [x] Remove aliases that are "also works with" not true aliases #3049
- [x] Remove `fixMarkup` (deprecated via #2534)
- [x] Remove `useBR` #2559
- [x] Remove `tabReplace` (deprecated via #2874)
- [x] Remove `php3`, 4, 5, 6, etc. aliases
- [x] Remove `sql_more` grammar
- [x] `relevance` returned by highlight is allowed to be a floating point number now
- [x] Remove HTML merging (deprecated via #2889)
- [x] Consider status of ESM support in Node #2600 
- [x] rename `regex.join` to indicate it's internal
- [x] remove `re` key from element.result (highlightBlock)
- [x] remove the old `htmlbars` stub
- [x] remove the old `c-like` stub
- [x] remove schoolbook or remove it's funky background [ref](https://github.com/highlightjs/highlight.js/pull/2923)
- [x] change default padding of all themes to be more generous
- [x] rename `second_best` to `secondBest`
- [x] remove apache, http, nginx, properties, coffeescript from `:common` https://github.com/highlightjs/highlight.js/issues/2848
- [x] move `CSS_NUMBER_MODE` into `css-shared` (it's too specific to be a general rule)
- [x] review notes on https://github.com/highlightjs/highlight.js/issues/2945 and consider making some attributes of Result "private"... ie, `__top` vs `top`... since those are intended more for debugging rather than public use.
- [x] `initHighlighting*` needs to be aliased to `highlightAll()`

**Comment by taufik-nurrohman** [comment]
- [ ] `hljs.listAliases()` &tarr; to get the complete list of aliases (with a map to the original language maybe?)
- [x] `hljs.listLanguages()`
- [ ] `hljs.listNames()` &rarr; to get the complete list of language names for human to be used in select box, etc.
- [x] `hljs.registerAlias()`
- [x] `hljs.registerLanguage()`

What do you think?

**Comment by yyyc514** [comment]
What good is `listNames` without the identifiers?  I'd think if anything `allLanguages` or something would be more helpful.

```js
var options = 
  allLanguages.map(lang => [lang.internalName, lang.prettyName])
```

But here we quickly hit the fact that our "names" are really nothing more than fancy aliases and languages honestly don't even know their "internal names" LOL.

I'd really rather see individual issues for suggesting new API and it's related discussion though... I don't believe inventing APIs in the abstract.  I'd rather have a concrete real-world use case that is impossible to solve now and someone TRULY needs to solve, and then focus on it.  Like the recent addition of `registerAlias`...

**Comment by yyyc514** [comment]
This isn't a general discussion thread for version 11 (esp not this early), it's more of a todo-list scratch pad for maintainers.  Please open a separate issue if you want to discuss an individual aspect of the future version 11 release.
