### ISSUE TITLE
TODO: Vue plugin moves to it's own repository

### ISSUE THREAD

**Issue by joshgoebel** [highlightjs/highlight.js#3067]
https://github.com/highlightjs/vue-plugin

- [x] move code
- [ ] publish to NPM
- [x] Remove from hljs source
- [x] update HLJS docs/readme

**Comment by joshgoebel** [comment]
0.9.0 released: https://github.com/highlightjs/vue-plugin
